config={
	interval=600,
	threshold=-620,
	night_shutter='15',
	zoom='0',
	archive_path='/root/archive/',
	camera_ID='B',
	upload_URL='http://domain.com/webcam/uploads/webcamup.php',
	user='user:password'
}
